    <div id="header">
      <a href="../heidi/portfolio.html"><img id="head-hm" class="nav-img" alt="Heidi Munc" src="../img/heidi/header-heidimunc.gif" /></a>
      <img id="head-empty" class="nav-img" alt="" src="../img/heidi/header-empty.gif" />
      <a href="../heidi/portfolio.html" onclick="swapContent('portfolio'); return false;"><img id="head-portfolio" class="nav-img" alt="Portfolio" src="../img/heidi/header-portfolio-a.gif" /></a>
      <a class="target-blank" href="../downloads/HeidiMunc.pdf"><!--TODO: What about &#233; in Resume image?--><img id="head-resume" class="nav-img" alt="Resum&#233;" src="../img/heidi/header-resume.gif" /></a>
      <a href="contactHeidi.html" onclick="processContactLink(); return false;"><img id="head-contact" class="nav-img" alt="Contact" src="../img/heidi/header-contact.gif" /></a>
    </div>