    <title>Heidi Munc - Portfolio</title>
    <meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8" />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="title" content="Heidi Munc's Portfolio" />
    <meta name="author" content="munc.com" />
    <meta name="robots" content="all" />
    <script type="text/javascript" src="../js/script.aculo.us/prototype.js"></script>
    <script type="text/javascript" src="../js/scriptaculous.js"></script>
    <script type="text/javascript" src="../js/heidi/portfolio.js"></script>
    <script type="text/javascript" src="../js/lightbox.js"></script>
    <link rel="stylesheet" href="../css/lightbox.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../css/heidi/portfolio.css" />
    <link rel="stylesheet" type="text/css" href="../css/heidi/images.css" />