    <div id="nav">
      <h3><a class="nav-header" href="#" onclick="Effect.toggle('branding', 'blind'); return false;"><img alt="Branding" src="../img/heidi/nav-branding.gif" /></a></h3>
      <div class="nav-section">
        <ul id="branding">
          <li><a href="aimGames.html" onclick="swapContent('aimGames'); return false;">AIM Games</a></li>
          <li><a href="nsBroadband1Brand.html" onclick="swapContent('nsBroadband1Brand'); return false;">NS Broadband I</a></li><!-- TODO: capitalization between sections... see print out-->
          <li><a href="nsBroadband2Brand.html" onclick="swapContent('nsBroadband2Brand'); return false;">NS Broadband II</a></li><!-- TODO: even the images are not capitalized-->
          <li><a href="netscapeIsp.html" onclick="swapContent('netscapeIsp'); return false;">Netscape ISP</a></li>
          <li><a href="nsUserIcons.html" onclick="swapContent('nsUserIcons'); return false;">NS User Icons</a></li>
        </ul>
      </div>
      <h3><a class="nav-header" href="#" onclick="Effect.toggle('webdesign', 'blind'); return false;"><img alt="Web Design" src="../img/heidi/nav-webdesign.gif" /></a></h3>
      <div class="nav-section">
        <ul id="webdesign">
          <li><a href="navigator.html" onclick="swapContent('navigator'); return false;">Navigator</a></li>
          <li><a href="nsBroadband1Web.html" onclick="swapContent('nsBroadband1Web'); return false;">NS Broadband I</a></li>
          <li><a href="sportsIllustrated.html" onclick="swapContent('sportsIllustrated'); return false;">Sports Illustrated</a></li>
          <li><a href="apple.html" onclick="swapContent('apple'); return false;">Apple</a></li>
          <li><a href="aim.html" onclick="swapContent('aim'); return false;">AIM</a></li>
          <li><a href="browser8Ads.html" onclick="swapContent('browser8Ads'); return false;">Browser 8.0 ads</a></li>
          <li><a href="nsBroadband2Web.html" onclick="swapContent('nsBroadband2Web'); return false;">NS Broadband II</a></li>
          <li><a href="nsChannels.html" onclick="swapContent('nsChannels'); return false;">NS Channels</a></li>
          <li><a href="nsHome2003.html" onclick="swapContent('nsHome2003'); return false;">NS Home 2003</a></li>
          <li><a href="nsHome2005.html" onclick="swapContent('nsHome2005'); return false;">NS Home 2005</a></li>
        </ul>
      </div>
      <h3><a class="nav-header" href="#" onclick="Effect.toggle('print', 'blind'); return false;"><img alt="Print" src="../img/heidi/nav-print.gif" /></a></h3>
      <div class="nav-section">
        <ul id="print">
          <li><a href="ibmBrochure.html" onclick="swapContent('ibmBrochure'); return false;">IBM Brochure</a></li>
          <li><a href="youngIsaac.html" onclick="swapContent('youngIsaac'); return false;">Young Isaac</a></li>
          <li><a href="cbusMuseum.html" onclick="swapContent('cbusMuseum'); return false;">Columbus<br />&nbsp;&nbsp;Museum of Art</a></li>
        </ul>
      </div>
      <h3><a class="nav-header" href="#" onclick="Effect.toggle('personal', 'blind'); return false;"><img alt="Personal" src="../img/heidi/nav-personal.gif" /></a></h3>
      <div class="nav-section">
        <ul id="personal">
          <li><a href="digitalMarquetryScreen.html" onclick="swapContent('digitalMarquetryScreen'); return false;">Digital Marquetry<br />&nbsp;&nbsp;Screen</a></li>
          <li><a href="kipsBayCabinet.html" onclick="swapContent('kipsBayCabinet'); return false;">Kip's Bay Cabinet</a></li>
          <li><a href="kipsBayDoor.html" onclick="swapContent('kipsBayDoor'); return false;">Kip's Bay Door</a></li>
          <li><a href="wallHanging.html" onclick="swapContent('wallHanging'); return false;">Wall Hanging</a></li>
          <li><a href="invitation.html" onclick="swapContent('invitation'); return false;">Invitation</a></li>
          <li><a href="photography.html" onclick="swapContent('photography'); return false;">Photography</a></li>
        </ul>
      </div>
    </div>
    <script type="text/javascript">
      <!-- // <![CDATA[
      //Note: If this is done in CSS, Scriptaculous cannot work with it.
      //Note: Two other potential advantages to it being here.
      //   1) If JavaScript is disabled, they will not be hidden.
      //   2) It keeps style further separated from the page content,
      //      compared to inline.
      $('branding').style.display = 'none';
      $('webdesign').style.display = 'none';
      $('print').style.display = 'none';
      $('personal').style.display = 'none';
      handleNewWindowLinks();
      // ]]> -->
    </script>